version: '3'

services:
    node-server:
        environment: 
            - NODE_ENV=development
        build:
            context: .
            args:
                - NODE_ENV=development
        command: npm run watch:dev