version: '3'

services:
    node-server:
        restart: always
        environment: 
            - NODE_ENV=production
        build:
            context: .
            args:
                - NODE_ENV=production
        command: npm start